### ISSUE TITLE
Problem connecting to Amazon Simple AD (does not support LDAPS)

### ISSUE THREAD

**Issue by thiloplanz** [wso2/carbon-identity#1621]
I am trying to set up Amazon Simple AD as a Primary User Store.

This is a version of Active Directory, but they do not support connecting via LDAPS.
http://stackoverflow.com/questions/34279085/how-to-connect-to-amazon-simple-ad-using-ldaps

As a result, Identity Server appears to be putting the LDAP connection into read-only mode:

     [2015-12-15 08:54:22,906]  WARN
      {org.wso2.carbon.user.core.ldap.ActiveDirectoryUserStoreManager} 
     -  Connection to the Active Directory is not secure. 
         Passowrd involved operations such as update credentials 
         and adduser operations will fail

Is there a workaround for this (a plain LDAP connection is probably safe in this case, as it goes over a virtual private network in the form of Amazon VPC) ?

**Comment by thiloplanz** [comment]
I found one workaround that seems to do it: Using `stunnel` ( https://www.stunnel.org/index.html )  to connect LDAPS on a local port to plain LDAP on Simple AD.

**Comment by IndunilRathnayake** [comment]
Hi,
This issue will be tracked in https://wso2.org/jira/browse/IDENTITY-4520, hence closing this entry.
Thanks
Indunil
