### ISSUE TITLE
EntitlementExtensionBuilder does not support AttributeFinder properties with comma in value

### ISSUE THREAD

**Issue by s-nel** [wso2/carbon-identity#1663]
The EntitlementExtensionBuilder only passes the first piece of each AttributeFinder property value if the value contains a comma. The flawed code is:

```Java
String[] props = properties.getProperty(className + "." + j++).split(",");
designatorProps.put(props[0], props[1]);
```

If my property is `foo.bar.MyAttributeFinder.1=key,hello,world` I would get the property `key` -> `hello` in my AttributeFinder.

The bug is repeated several times in EntitlementExtensionBuilder.

**Comment by IndunilRathnayake** [comment]
Hi,
This issue will be tracked in https://wso2.org/jira/browse/IDENTITY-4518, hence closing this entry.
Thanks
Indunil
