### ISSUE TITLE
EntitlementExtensionBuilder does not support multiple instances of same Attribute Finder with different configuration

### ISSUE THREAD

**Issue by s-nel** [wso2/carbon-identity#1670]
If I build a generic attribute finder that can support multiple uses, there is no way to distinguish between two instances in configuration. E.g. I specify the two finders in entitlement.properties

PIP.AttributeDesignators.Designator.1=foo.Bar
PIP.AttributeDesignators.Designator.2=foo.Bar

To supply each instance with configuration I define properties:

foo.Bar.1=property,value

Since the property names are based on the class name of the attribute finder, there is no way to supply different configuration for each instance. This severely limits the reusability of attribute finders.

**Comment by IndunilRathnayake** [comment]
Hi,
This issue will be tracked in https://wso2.org/jira/browse/IDENTITY-4517, hence closing this entry.
Thanks
Indunil
