### ISSUE TITLE
Customizing AuthenticationRequestHandler extension point seems not to be working

### ISSUE THREAD

**Issue by lovoni** [wso2/carbon-identity#1720]
In application-authentication.xml I have the following line:
&lt;AuthenticationRequestHandler>p.q.MyAuthentRequestHandler&lt;/AuthenticationRequestHandler>

MyAuthentRequestHandler is never invoked as expected.

Bellow is the code in org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils.java

How come we test obj against LogoutRequestHandler type then cast it into AuthenticationRequestHandler ?

Thanks for your reply.

Best regards.

    /**
     * @return
     */
    public static AuthenticationRequestHandler getAuthenticationRequestHandler() {

        AuthenticationRequestHandler authenticationRequestHandler = null;
        Object obj = ConfigurationFacade.getInstance().getExtensions()
                .get(FrameworkConstants.Config.QNAME_EXT_AUTH_REQ_HANDLER);

        if (obj instanceof LogoutRequestHandler) {
            authenticationRequestHandler = (AuthenticationRequestHandler) obj;
        } else {
            authenticationRequestHandler = DefaultAuthenticationRequestHandler.getInstance();
        }

        return authenticationRequestHandler;
    }

    /**
     * @return
     */
    public static LogoutRequestHandler getLogoutRequestHandler() {

        LogoutRequestHandler logoutRequestHandler = null;
        Object obj = ConfigurationFacade.getInstance().getExtensions()
                .get(FrameworkConstants.Config.QNAME_EXT_LOGOUT_REQ_HANDLER);

        if (obj instanceof AuthenticationRequestHandler) {
            logoutRequestHandler = (LogoutRequestHandler) obj;
        } else {
            logoutRequestHandler = DefaultLogoutRequestHandler.getInstance();
        }

        return logoutRequestHandler;
    }

**Comment by IndunilRathnayake** [comment]
Hi,
The issue in the code segment which you have pointed out, is  currently fixed (https://github.com/wso2/carbon-identity/pull/272/files), hence closing this entry.
Thanks
Indunil
