### ISSUE TITLE
persisted session DO timestamp is not correct

### ISSUE THREAD

**Issue by gusto2** [wso2/carbon-identity#1743]
in the class org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SessionDataStore.java the time_created is computed as:

 currentStandardNano = currentStandardNano + (currentSystemNano - FrameworkServiceDataHolder.getInstance().getNanoTimeReference());

which after certain time (e.g. 2 days) places all timestamps 2 days in future. A simple nano should suffice (is there even any reason to use nanosecods?)

**Comment by cdwijayarathna** [comment]
Closing this referring to conversation at https://github.com/wso2/carbon-identity/pull/1744
