### ISSUE TITLE
Unable to get PostalCode, DOB, Title in SAML Post of WSO2 IS

### ISSUE THREAD

**Issue by JavaHelper** [wso2/carbon-identity#942]
Could anyone please help me for the issue http://stackoverflow.com/questions/32506781/unable-to-register-postalcode-tiltle-locality-and-dob-in-user-profile-of-wso2?

**Comment by IndunilRathnayake** [comment]
Hi,
For that you need to configure new claim mappings for PostalCode, DOB andTitle and map your new claim URIs to attributes of the underlying user store. If you need to show new claims in the user profile UI, you need to tick on the "Supported by Default" check box in claim mapping configuration. For more details, you can refer https://docs.wso2.com/display/IS510/Configuring+Claims.
Thanks
Indunil
